version: '3'

services:
  web:
    image: christsent/php-mysql-apache # Use an official PHP image with Apache
    container_name: php_app2
    volumes:
      - ./challenge/:/var/www/html # Mount your PHP application code
    ports:
      - 5001:80 # Map container port 80 to host port 8080
    depends_on:
      - db_mysql # Make sure the web container starts after the database container
    networks:
      - mynetwork

  db_mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: KSA
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306
    networks:
      - mynetwork

    volumes:
      - ./init:/docker-entrypoint-initdb.d




networks:
  mynetwork:
